# auto: true

markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title
encoding: UTF-8
gems: [jekyll-paginate]

title: Let My Fire
url: http://missword2012.github.io
feed: /atom.xml
author_info: <a href="http://missword2012.github.io/">shangyou</a>

myblog:
  gavatar: images/2.jpg
  gpname: shangyou
  linkedin: 
  github: https://github.com/missword2012
  email: mailto:missword2012@163.com
  coverimgs: []
  postbgimg: []

categories: [python, books]
